### ISSUE TITLE
New user setup

### ISSUE THREAD

**Issue by davesade** [do-team/endleg#12]
When new user is registered, we need to create basic record in table. Can we invoke this somehow with Userpool / Federated identity registration?

**Comment by martinsalaj** [comment]
Maybe this http://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html

**Comment by davesade** [comment]
Thanks for a tip! I knew it was there. Script created (see endleg-init), it was pretty straight forward.
